import fs from 'fs';
import os from 'os';
import path from 'path';

import { runWrapperFromStdin, writeOutput } from './codex-wrapper.js';

type McpServerConfig = {
  command: string;
  args?: string[];
  env?: Record<string, string>;
  required?: boolean;
};

const MANAGED_BLOCK_START = '# >>> nanoclaw managed mcp servers >>>';
const MANAGED_BLOCK_END = '# <<< nanoclaw managed mcp servers <<<';

const allowedTools = [
  'mcp__nanoclaw__*',
  'mcp__ollama__*',
];

const mcpServers: Record<string, McpServerConfig> = {
  nanoclaw: {
    command: 'node',
    args: ['/tmp/dist/ipc-mcp-stdio.js'],
    env: {
      NANOCLAW_CHAT_JID: process.env.NANOCLAW_CHAT_JID ?? '',
      NANOCLAW_GROUP_FOLDER: process.env.NANOCLAW_GROUP_FOLDER ?? '',
      NANOCLAW_IS_MAIN: process.env.NANOCLAW_IS_MAIN ?? '0',
    },
    required: true,
  },
  ollama: {
    command: 'node',
    args: ['/tmp/dist/ollama-mcp-stdio.js'],
  },
};

function escapeTomlString(value: string): string {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n');
}

function renderTomlArray(values: string[]): string {
  return `[${values.map((value) => `"${escapeTomlString(value)}"`).join(', ')}]`;
}

function renderTomlInlineTable(values: Record<string, string>): string {
  const entries = Object.entries(values).filter(([, value]) => value.length > 0);
  return `{ ${entries
    .map(([key, value]) => `${key} = "${escapeTomlString(value)}"`)
    .join(', ')} }`;
}

function renderManagedConfig(): string {
  const lines = [MANAGED_BLOCK_START, '# Generated by NanoClaw container runner.'];

  if (allowedTools.length > 0) {
    lines.push(`# allowed_tools = ${renderTomlArray(allowedTools)}`);
  }

  for (const [serverName, serverConfig] of Object.entries(mcpServers)) {
    lines.push('', `[mcp_servers.${serverName}]`);
    lines.push(`command = "${escapeTomlString(serverConfig.command)}"`);
    if (serverConfig.args && serverConfig.args.length > 0) {
      lines.push(`args = ${renderTomlArray(serverConfig.args)}`);
    }
    if (serverConfig.env) {
      lines.push(`env = ${renderTomlInlineTable(serverConfig.env)}`);
    }
    if (serverConfig.required != null) {
      lines.push(`required = ${serverConfig.required ? 'true' : 'false'}`);
    }
  }

  lines.push('', MANAGED_BLOCK_END, '');
  return lines.join('\n');
}

function ensureCodexConfig(): void {
  const codexHome = path.join(process.env.HOME || os.homedir(), '.codex');
  const configPath = path.join(codexHome, 'config.toml');
  fs.mkdirSync(codexHome, { recursive: true });

  const existing = fs.existsSync(configPath)
    ? fs.readFileSync(configPath, 'utf-8')
    : '';
  const withoutManagedBlock = existing.replace(
    new RegExp(
      `${MANAGED_BLOCK_START}[\\s\\S]*?${MANAGED_BLOCK_END}\\n?`,
      'g',
    ),
    '',
  ).trimEnd();

  const next = withoutManagedBlock
    ? `${withoutManagedBlock}\n\n${renderManagedConfig()}`
    : renderManagedConfig();
  fs.writeFileSync(configPath, next);
}

const result = await (async () => {
  try {
    ensureCodexConfig();
    return await runWrapperFromStdin(process.stdin);
  } catch (error) {
    return {
      exitCode: 1,
      output: {
        status: 'error' as const,
        result: null,
        message:
          error instanceof Error ? error.message : 'CODEX_ENTRYPOINT_FAILURE',
      },
    };
  }
})();

writeOutput(result.output);
process.exit(result.exitCode);
